Xpos334/Xpos334/Controllers/CategoryTryController.cs
using Microsoft.AspNetCore.Mvc;
using xpos334.datamodels;
using xpos334.viewmodels;
using Xpos334.Models;
using Xpos334.Services;

namespace Xpos334.Controllers

{
    public class CategoryTryController : Controller
    {

        private readonly XPOS_334Context db;
        private readonly CategoryTryService categoryServices;

        public CategoryTryController(XPOS_334Context _db)
        {
            db = _db;
            this.categoryServices = new CategoryTryService(db);
        }

        public IActionResult Index()
        {
            List<VMTblCategory> dataView = categoryServices.GetAllData();
            return View(dataView);
        }

        public IActionResult Create()
        {
            VMTblCategory dataView = new VMTblCategory();
            return PartialView(dataView);
        }

        [HttpPost]
        public IActionResult Create(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();
            if (ModelState.IsValid)
            {
                respon = categoryServices.Create(dataView);

                if (respon.Success)
                {
                    return RedirectToAction("Index");

                }
            }
            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Edit(int id)
        {
            VMTblCategory dataView = categoryServices.GetById(id);
            return PartialView(dataView);
        }

        [HttpPost]
        public IActionResult Edit(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();
            if (ModelState.IsValid)
            {
                respon = categoryServices.Edit(dataView);
                if (respon.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Detail(int id)
        {
            VMTblCategory dataView = categoryServices.GetById(id);
            //ViewBag.tbl_category = dataView;//contoh penggunaan viewbag
            return PartialView(dataView);//contoh penggunaan return view
            //return PartialView();
        }

        public IActionResult Delete(int id)
        {
            VMTblCategory dataView = categoryServices.GetById(id);
            //ViewBag.tbl_category = dataView;//contoh penggunaan viewbag
            return PartialView(dataView);//contoh penggunaan return view
            //return PartialView();
        }

        [HttpPost]
        public IActionResult Delete(VMTblCategory dataView)
        {
            VMResponse respon = categoryServices.Delete(dataView);
            if (respon.Success)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(respon.Entity);
            }
         
        }


    }
}

Xpos334/Xpos334/Views/CategoryTry/Create.cshtml
@using xpos334.viewmodels;

@model VMTblCategory

@{
    //Layout = null;
    ViewData["Title"] = "Create Category Try";
}
<div class="card">
    <div class="card-body">

        <div class="h4 mb-4" @ViewData["Title"]></div>

     <form asp-action="Create" method="post">
        <div class="mb-4 row ">
            <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="NameCategory" Name="NameCategory" value="@Model.NameCategory">
                <span asp-validation-for="NameCategory" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-4 row ">
            <label for="Description" class="col-sm-4 col-form-label">Description</label>
            <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" Name="Description" value="@Model.Description">
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>




        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a class="btn btn-outline-primary" asp-controller="CategoryTry" asp-action="Index">Back To List</a>
            </div>
        </div>


      </form>
    </div>
</div>

Xpos334/Xpos334/Views/CategoryTry/Delete.cshtml
@{
    ViewData["Title"] = "Delete Category Try";
}

<div class="card">
    <div class="card-body">

        <form asp-action="Delete" method="post">

            <input type="hidden" class="form-control" id="Id" Name="Id" value="@Model.Id">


            <div class="h3 mb-4 row">Are you sure for delete @Model.NameCategory ?</div>


            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-outline-primary" asp-controller="CategoryTry" asp-action="Index">Back To List</a>
                </div>
            </div>

        </form>


    </div>
</div>

Xpos334/Xpos334/Views/CategoryTry/Detail.cshtml
@using xpos334.viewmodels;

@model VMTblCategory

@{
    ViewData["Title"] = "Detail Category Try";
}

<div class="card">
    <div class="card-body">

        <div class="h4 mb-4" @ViewData["Title"]></div>

            <div class="mb-4 row ">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" Name="NameCategory" value="@Model.NameCategory" readonly>
                    @* <input type="text" class="form-control" id="NameCategory" Name="NameCategory" value="@ViewBag.tbl_category.NameCategory" readonly> *@

                </div>
            </div>
            <div class="mb-4 row ">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" Name="Description" value="@Model.Description" readonly>
                @* <input type="text" class="form-control" id="Description" Name="Description" value="@ViewBag.tbl_category.Description" readonly> *@

                </div>
            </div>



            <div class="form-group row">
                <div class="col-sm-10">

                    <a class="btn btn-outline-primary" asp-controller="CategoryTry" asp-action="Index">Back To List</a>
                </div>
            </div>


    </div>
</div>

Xpos334/Xpos334/Views/CategoryTry/Edit.cshtml
@using xpos334.viewmodels;

@model VMTblCategory

@{
    ViewData["Title"] = "Edit Category Try";
}

<div class="card">
    <div class="card-body">

        <div class="h4 mb-4" @ViewData["Title"]></div>

        <form asp-action="Edit" method="post">

            <input type="hidden" class="form-control" id="Id" Name="Id" value="@Model.Id">

            <div class="mb-4 row ">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" Name="NameCategory" value="@Model.NameCategory">
                    <span asp-validation-for="NameCategory" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-4 row ">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" Name="Description" value="@Model.Description">
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>



            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-outline-primary" asp-controller="CategoryTry" asp-action="Index">Back To List</a>
                </div>
            </div>


        </form>
    </div>
</div>

Xpos334/Xpos334/Views/CategoryTry/Index.cshtml
@using xpos334.viewmodels;

@{
    ViewData["Title"] = "Category Try";
}


<div class="card">
    <div class="card-body">
        <h5 class="card-title">@ViewData["Title"]</h5>

        <button type="button" class="btn btn-outline-primary" id="btn_create">Create</button>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name Category</th>
                    <th scope="col">Description</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (VMTblCategory item in Model){

                <tr>
                    <td scope="row">@item.Id</td>
                    <td>@item.NameCategory</td>
                    <td>@item.Description</td>
                    <td>
                        <a class="btn btn-outline-primary btn_edit" data-id="@item.Id">Edit</a>
                        <a class="btn btn-outline-success btn_detail" data-id="@item.Id">Detail</a>
                            <a class="btn btn-outline-danger btn_delete" data-id="@item.Id">Delete</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>

    </div>
</div>


<script>
    $("#btn_create").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/CategoryTry/Create")
        $("#my_modal").modal("show")
    })

    $(".btn_edit").click(function () {
        var id = $(this).data("id")

        $("#modal_body").empty()
        $("#modal_body").load("/CategoryTry/Edit?id=" + id)
        $("#my_modal").modal("show")

    })

    $(".btn_detail").click(function () {
        var id = $(this).data("id")

        $("#modal_body").empty()
        $("#modal_body").load("/CategoryTry/Detail?id=" + id)
        $("#my_modal").modal("show")

    })

    $(".btn_delete").click(function () {
        var id = $(this).data("id")

        $("#modal_body").empty()
        $("#modal_body").load("/CategoryTry/Delete?id=" + id)
        $("#my_modal").modal("show")

    })


</script>